# Generated by Django 4.2.26 on 2025-11-12 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feature",
            options={
                "verbose_name": "Feature (Legacy)",
                "verbose_name_plural": "Features (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="initiative",
            options={
                "verbose_name": "Initiative (Legacy)",
                "verbose_name_plural": "Initiatives (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="portfolio",
            options={
                "verbose_name": "Portfolio (Legacy)",
                "verbose_name_plural": "Portfolios (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "verbose_name": "Product (Legacy)",
                "verbose_name_plural": "Products (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="vision",
            options={
                "verbose_name": "Vision (Legacy)",
                "verbose_name_plural": "Visions (Legacy)",
            },
        ),
        migrations.AlterField(
            model_name="workflowstep",
            name="step_type",
            field=models.CharField(
                choices=[
                    ("market_context", "Market Context"),
                    ("discovery_research", "Discovery Research"),
                    ("problem_definition", "Problem Definition"),
                    ("hypothesis_business_case", "Hypothesis & Business Case"),
                    ("success_metrics", "Success Metrics & Guardrails"),
                    ("stakeholder_buyin", "Stakeholder Buy-In"),
                    ("ideation_solution_design", "Ideation & Solution Design"),
                    ("prd_requirements", "PRD / Requirements Definition"),
                    ("design_prototypes", "Design Prototypes + Validation"),
                    ("development", "Development"),
                    ("qa_uat_staging", "QA, UAT, and Staging"),
                    ("gtm_planning", "Go-to-Market Planning"),
                    ("release_execution", "Release Execution"),
                    ("post_launch_validation", "Post-Launch Validation"),
                    ("retrospective", "Retrospective & Learnings"),
                    ("vision", "Vision (Legacy)"),
                    ("initiative", "Initiative (Legacy)"),
                    ("portfolio", "Portfolio (Legacy)"),
                    ("product", "Product (Legacy)"),
                    ("feature", "Feature (Legacy)"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="SuccessMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leading_indicators",
                    models.TextField(blank=True, help_text="Early signals of success"),
                ),
                (
                    "lagging_indicators",
                    models.TextField(blank=True, help_text="Long-term success metrics"),
                ),
                (
                    "guardrail_metrics",
                    models.TextField(
                        blank=True, help_text="Metrics that should not degrade"
                    ),
                ),
                (
                    "workflow_step",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="success_metrics_details",
                        to="product_management.workflowstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Success Metrics",
                "verbose_name_plural": "Success Metrics",
            },
        ),
        migrations.CreateModel(
            name="StakeholderBuyIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "executive_alignment",
                    models.TextField(
                        blank=True, help_text="Executive approval and alignment"
                    ),
                ),
                (
                    "budget_approval",
                    models.TextField(
                        blank=True, help_text="Budget details and approval"
                    ),
                ),
                (
                    "resource_allocation",
                    models.TextField(
                        blank=True, help_text="Team and resource commitments"
                    ),
                ),
                (
                    "workflow_step",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stakeholder_buyin_details",
                        to="product_management.workflowstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stakeholder Buy-In",
                "verbose_name_plural": "Stakeholder Buy-Ins",
            },
        ),
        migrations.CreateModel(
            name="Retrospective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outcomes_vs_hypothesis",
                    models.TextField(
                        blank=True, help_text="Did we achieve what we expected?"
                    ),
                ),
                (
                    "what_went_well",
                    models.TextField(blank=True, help_text="What worked well"),
                ),
                (
                    "what_to_improve",
                    models.TextField(blank=True, help_text="Areas for improvement"),
                ),
                (
                    "key_learnings",
                    models.TextField(
                        blank=True, help_text="Key takeaways and learnings"
                    ),
                ),
                (
                    "workflow_step",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retrospective_details",
                        to="product_management.workflowstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retrospective & Learnings",
                "verbose_name_plural": "Retrospectives & Learnings",
            },
        ),
        migrations.CreateModel(
            name="ReleaseExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rollout_plan",
                    models.TextField(
                        blank=True, help_text="Phased rollout or A/B test plan"
                    ),
                ),
                (
                    "monitoring_setup",
                    models.TextField(
                        blank=True, help_text="Real-time monitoring configuration"
                    ),
                ),
                (
                    "rollout_status",
                    models.TextField(
                        blank=True, help_text="Current rollout status and notes"
                    ),
                ),
                (
                    "workflow_step",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="release_execution_details",
                        to="product_management.workflowstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Release Execution",
                "verbose_name_plural": "Release Execution",
            },
        ),
        migrations.CreateModel(
            name="QAUATStaging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_plan",
                    models.TextField(blank=True, help_text="Testing plan and approach"),
                ),
                (
                    "qa_results",
                    models.TextField(blank=True, help_text="QA testing results"),
                ),
                (
                    "uat_feedback",
                    models.TextField(
                        blank=True, help_text="User acceptance testing feedback"
                    ),
                ),
                (
                    "bug_triage",
                    models.TextField(blank=True, help_text="Bug triage and resolution"),
                ),
                (
                    "workflow_step",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qa_uat_staging_details",
                        to="product_management.workflowstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "QA, UAT, and Staging",
                "verbose_name_plural": "QA, UAT, and Staging",
            },
        ),
        migrations.CreateModel(
            name="ProblemDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "core_pain_point",
                    models.TextField(
                        blank=True, help_text="The core pain point to solve"
                    ),
                ),
                (
                    "affected_personas",
                    models.TextField(blank=True, help_text="User personas affected"),
                ),
                (
                    "problem_statement",
                    models.TextField(blank=True, help_text="Clear problem statement"),
                ),
                (
                    "workflow_step",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_definition_details",
                        to="product_management.workflowstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Problem Definition",
                "verbose_name_plural": "Problem Definitions",
            },
        ),
        migrations.CreateModel(
            name="PRDRequirements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "problem_statement",
                    models.TextField(blank=True, help_text="The problem being solved"),
                ),
                (
                    "goals",
                    models.TextField(blank=True, help_text="Goals and objectives"),
                ),
                (
                    "constraints",
                    models.TextField(
                        blank=True, help_text="Technical and business constraints"
                    ),
                ),
                (
                    "user_stories",
                    models.TextField(blank=True, help_text="User stories"),
                ),
                (
                    "acceptance_criteria",
                    models.TextField(blank=True, help_text="Acceptance criteria"),
                ),
                (
                    "workflow_step",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prd_requirements_details",
                        to="product_management.workflowstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "PRD / Requirements",
                "verbose_name_plural": "PRD / Requirements",
            },
        ),
        migrations.CreateModel(
            name="PostLaunchValidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metrics_results",
                    models.TextField(
                        blank=True, help_text="Actual metrics vs. targets"
                    ),
                ),
                (
                    "user_surveys",
                    models.TextField(blank=True, help_text="User survey results"),
                ),
                (
                    "performance_monitoring",
                    models.TextField(
                        blank=True, help_text="Performance and stability monitoring"
                    ),
                ),
                (
                    "workflow_step",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_launch_validation_details",
                        to="product_management.workflowstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post-Launch Validation",
                "verbose_name_plural": "Post-Launch Validations",
            },
        ),
        migrations.CreateModel(
            name="MarketContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "market_trends",
                    models.TextField(
                        blank=True, help_text="Current market trends and dynamics"
                    ),
                ),
                (
                    "competitive_positioning",
                    models.TextField(
                        blank=True, help_text="Competitive landscape analysis"
                    ),
                ),
                (
                    "customer_segments",
                    models.TextField(blank=True, help_text="Target customer segments"),
                ),
                (
                    "workflow_step",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_context_details",
                        to="product_management.workflowstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Market Context",
                "verbose_name_plural": "Market Contexts",
            },
        ),
        migrations.CreateModel(
            name="IdeationSolutionDesign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "design_concepts",
                    models.TextField(blank=True, help_text="Design concepts and ideas"),
                ),
                (
                    "solution_approaches",
                    models.TextField(
                        blank=True, help_text="Potential solution approaches"
                    ),
                ),
                (
                    "collaboration_notes",
                    models.TextField(
                        blank=True, help_text="Notes from design collaboration"
                    ),
                ),
                (
                    "workflow_step",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ideation_solution_design_details",
                        to="product_management.workflowstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ideation & Solution Design",
                "verbose_name_plural": "Ideation & Solution Designs",
            },
        ),
        migrations.CreateModel(
            name="HypothesisBusinessCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hypothesis",
                    models.TextField(
                        blank=True, help_text="What we believe will work and why"
                    ),
                ),
                (
                    "estimated_revenue_impact",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "estimated_cost_savings",
                    models.CharField(blank=True, max_length=255),
                ),
                ("engagement_impact", models.TextField(blank=True)),
                (
                    "estimated_effort",
                    models.TextField(
                        blank=True, help_text="Time, resources, complexity"
                    ),
                ),
                (
                    "strategic_alignment",
                    models.TextField(
                        blank=True, help_text="How this aligns with OKRs and goals"
                    ),
                ),
                (
                    "workflow_step",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hypothesis_business_case_details",
                        to="product_management.workflowstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hypothesis & Business Case",
                "verbose_name_plural": "Hypothesis & Business Cases",
            },
        ),
        migrations.CreateModel(
            name="GTMPlanning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "launch_strategy",
                    models.TextField(blank=True, help_text="Overall launch strategy"),
                ),
                (
                    "communications_plan",
                    models.TextField(
                        blank=True, help_text="Internal and external communications"
                    ),
                ),
                (
                    "training_materials",
                    models.TextField(
                        blank=True, help_text="Training and documentation"
                    ),
                ),
                (
                    "marketing_materials",
                    models.TextField(
                        blank=True, help_text="Marketing assets and campaigns"
                    ),
                ),
                (
                    "workflow_step",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gtm_planning_details",
                        to="product_management.workflowstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Go-to-Market Planning",
                "verbose_name_plural": "Go-to-Market Planning",
            },
        ),
        migrations.CreateModel(
            name="DiscoveryResearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_interviews",
                    models.TextField(
                        blank=True, help_text="Summary of user interviews"
                    ),
                ),
                (
                    "data_analysis",
                    models.TextField(blank=True, help_text="Data analysis findings"),
                ),
                (
                    "support_tickets",
                    models.TextField(blank=True, help_text="Support ticket insights"),
                ),
                (
                    "workflow_step",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discovery_research_details",
                        to="product_management.workflowstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discovery Research",
                "verbose_name_plural": "Discovery Researches",
            },
        ),
        migrations.CreateModel(
            name="Development",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "technical_approach",
                    models.TextField(
                        blank=True, help_text="Technical implementation approach"
                    ),
                ),
                (
                    "sprint_plan",
                    models.TextField(
                        blank=True, help_text="Sprint planning and milestones"
                    ),
                ),
                (
                    "dependencies",
                    models.TextField(blank=True, help_text="Technical dependencies"),
                ),
                (
                    "progress_notes",
                    models.TextField(
                        blank=True, help_text="Development progress notes"
                    ),
                ),
                (
                    "workflow_step",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="development_details",
                        to="product_management.workflowstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Development",
                "verbose_name_plural": "Development",
            },
        ),
        migrations.CreateModel(
            name="DesignPrototypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prototype_links",
                    models.TextField(
                        blank=True, help_text="Links to prototypes and designs"
                    ),
                ),
                (
                    "usability_testing",
                    models.TextField(blank=True, help_text="Usability testing results"),
                ),
                (
                    "feedback_summary",
                    models.TextField(blank=True, help_text="Feedback from reviews"),
                ),
                (
                    "workflow_step",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_prototypes_details",
                        to="product_management.workflowstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Design Prototypes",
                "verbose_name_plural": "Design Prototypes",
            },
        ),
    ]
