# Generated by Django 4.2.26 on 2025-11-12 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "product_management",
            "0002_alter_feature_options_alter_initiative_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("market_context", "Market Context"),
                            ("discovery_research", "Discovery Research"),
                            ("problem_definition", "Problem Definition"),
                            ("hypothesis_business_case", "Hypothesis & Business Case"),
                            ("success_metrics", "Success Metrics & Guardrails"),
                            ("stakeholder_buyin", "Stakeholder Buy-In"),
                            ("ideation_design", "Ideation & Solution Design"),
                            ("prd_requirements", "PRD / Requirements Definition"),
                            ("design_prototypes", "Design Prototypes + Validation"),
                            ("development", "Development"),
                            ("qa_uat", "QA, UAT, and Staging"),
                            ("gtm_planning", "Go-to-Market Planning"),
                            ("release_execution", "Release Execution"),
                            ("post_launch", "Post-Launch Validation"),
                            ("retrospective", "Retrospective & Learnings"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "layer",
                    models.CharField(
                        choices=[
                            ("strategic", "Strategic / Discovery Layer"),
                            ("tactical", "Tactical / Build Layer"),
                            ("release", "Release / Impact Layer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("conversation_history", models.JSONField(blank=True, default=list)),
                ("document_content", models.TextField(blank=True)),
                ("document_generated_at", models.DateTimeField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product Step",
                "verbose_name_plural": "Product Steps",
                "ordering": ["product", "order", "created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="development",
            name="workflow_step",
        ),
        migrations.RemoveField(
            model_name="discoveryresearch",
            name="workflow_step",
        ),
        migrations.RemoveField(
            model_name="gtmplanning",
            name="workflow_step",
        ),
        migrations.RemoveField(
            model_name="hypothesisbusinesscase",
            name="workflow_step",
        ),
        migrations.RemoveField(
            model_name="ideationsolutiondesign",
            name="workflow_step",
        ),
        migrations.RemoveField(
            model_name="marketcontext",
            name="workflow_step",
        ),
        migrations.RemoveField(
            model_name="postlaunchvalidation",
            name="workflow_step",
        ),
        migrations.RemoveField(
            model_name="prdrequirements",
            name="workflow_step",
        ),
        migrations.RemoveField(
            model_name="problemdefinition",
            name="workflow_step",
        ),
        migrations.RemoveField(
            model_name="qauatstaging",
            name="workflow_step",
        ),
        migrations.RemoveField(
            model_name="releaseexecution",
            name="workflow_step",
        ),
        migrations.RemoveField(
            model_name="retrospective",
            name="workflow_step",
        ),
        migrations.RemoveField(
            model_name="stakeholderbuyin",
            name="workflow_step",
        ),
        migrations.RemoveField(
            model_name="successmetrics",
            name="workflow_step",
        ),
        migrations.AlterModelOptions(
            name="feature",
            options={"verbose_name": "Feature", "verbose_name_plural": "Features"},
        ),
        migrations.AlterModelOptions(
            name="initiative",
            options={
                "verbose_name": "Initiative",
                "verbose_name_plural": "Initiatives",
            },
        ),
        migrations.AlterModelOptions(
            name="portfolio",
            options={"verbose_name": "Portfolio", "verbose_name_plural": "Portfolios"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
        migrations.AlterModelOptions(
            name="vision",
            options={"verbose_name": "Vision", "verbose_name_plural": "Visions"},
        ),
        migrations.AlterField(
            model_name="workflowstep",
            name="step_type",
            field=models.CharField(
                choices=[
                    ("vision", "Vision"),
                    ("initiative", "Initiative"),
                    ("portfolio", "Portfolio"),
                    ("product", "Product"),
                    ("feature", "Feature"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="DesignPrototypes",
        ),
        migrations.DeleteModel(
            name="Development",
        ),
        migrations.DeleteModel(
            name="DiscoveryResearch",
        ),
        migrations.DeleteModel(
            name="GTMPlanning",
        ),
        migrations.DeleteModel(
            name="HypothesisBusinessCase",
        ),
        migrations.DeleteModel(
            name="IdeationSolutionDesign",
        ),
        migrations.DeleteModel(
            name="MarketContext",
        ),
        migrations.DeleteModel(
            name="PostLaunchValidation",
        ),
        migrations.DeleteModel(
            name="PRDRequirements",
        ),
        migrations.DeleteModel(
            name="ProblemDefinition",
        ),
        migrations.DeleteModel(
            name="QAUATStaging",
        ),
        migrations.DeleteModel(
            name="ReleaseExecution",
        ),
        migrations.DeleteModel(
            name="Retrospective",
        ),
        migrations.DeleteModel(
            name="StakeholderBuyIn",
        ),
        migrations.DeleteModel(
            name="SuccessMetrics",
        ),
        migrations.AddField(
            model_name="productstep",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_steps",
                to="product_management.product",
            ),
        ),
        migrations.AddIndex(
            model_name="productstep",
            index=models.Index(
                fields=["product", "step_type"], name="product_man_product_a4a1a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productstep",
            index=models.Index(
                fields=["product", "order"], name="product_man_product_0b9127_idx"
            ),
        ),
    ]
