# Generated by Django 4.2.26 on 2025-11-13 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "product_management",
            "0003_productstep_remove_development_workflow_step_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("requirements", "Requirements & Specifications"),
                            ("user_story", "User Story Definition"),
                            ("acceptance_criteria", "Acceptance Criteria"),
                            ("technical_design", "Technical Design"),
                            ("implementation", "Implementation"),
                            ("testing", "Testing & QA"),
                            ("code_review", "Code Review"),
                            ("documentation", "Documentation"),
                            ("deployment", "Deployment"),
                            ("validation", "User Validation"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "layer",
                    models.CharField(
                        choices=[
                            ("planning", "Planning Layer"),
                            ("development", "Development Layer"),
                            ("delivery", "Delivery Layer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("conversation_history", models.JSONField(blank=True, default=list)),
                ("document_content", models.TextField(blank=True)),
                ("document_generated_at", models.DateTimeField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_steps",
                        to="product_management.feature",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Step",
                "verbose_name_plural": "Feature Steps",
                "ordering": ["feature", "order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["feature", "step_type"],
                        name="product_man_feature_0d9bd2_idx",
                    ),
                    models.Index(
                        fields=["feature", "order"],
                        name="product_man_feature_8e3e56_idx",
                    ),
                ],
            },
        ),
    ]
