# Generated by Django 4.2.26 on 2025-11-13 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0004_featurestep"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowstep",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflow_steps",
                to="product_management.project",
            ),
        ),
    ]
