# Generated by Django 4.2.26 on 2025-11-13 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product_management", "0005_alter_workflowstep_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstep",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflow_steps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
