# Generated by Django 4.2.26 on 2025-11-13 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product_management", "0006_workflowstep_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("product", "Product"),
                            ("feature", "Feature"),
                            ("project", "Project"),
                            ("workflow", "Workflow Step"),
                        ],
                        max_length=20,
                    ),
                ),
                ("item_id", models.PositiveIntegerField()),
                ("item_title", models.CharField(max_length=255)),
                ("item_url", models.CharField(max_length=500)),
                ("accessed_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recent_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recent Item",
                "verbose_name_plural": "Recent Items",
                "ordering": ["-accessed_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-accessed_at"],
                        name="product_man_user_id_0184d1_idx",
                    )
                ],
                "unique_together": {("user", "item_type", "item_id")},
            },
        ),
    ]
