# Generated by Django 4.2.26 on 2025-11-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0007_recentitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstep",
            name="reference_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
