# Generated by Django 4.2.26 on 2025-11-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0008_workflowstep_reference_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstep",
            name="status",
            field=models.CharField(
                choices=[
                    ("backlog", "Backlog"),
                    ("todo", "To Do"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="backlog",
                max_length=20,
            ),
        ),
    ]
