# Generated by Django 4.2.26 on 2025-11-20 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product_management", "0009_workflowstep_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="product_management.workflowstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Comment",
                "verbose_name_plural": "Workflow Comments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workflow_step", "-created_at"],
                        name="product_man_workflo_cf26d6_idx",
                    )
                ],
            },
        ),
    ]
