# Generated by Django 4.2.26 on 2025-11-20 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product_management", "0010_workflowcomment"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("readme", "README"),
                            ("summary", "Summary"),
                            ("spec", "Specification"),
                            ("other", "Other"),
                        ],
                        default="readme",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("source", models.CharField(default="ai", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="product_management.workflowstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Document",
                "verbose_name_plural": "Workflow Documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workflow_step", "-created_at"],
                        name="product_man_workflo_a3843e_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkflowActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("comment_added", "Comment Added"),
                            ("description_updated", "Description Updated"),
                            ("title_updated", "Title Updated"),
                            ("readme_generated", "README Generated"),
                            ("step_completed", "Step Completed"),
                            ("code_change_requested", "Code Change Requested"),
                            ("document_saved", "Document Saved"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_action_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_logs",
                        to="product_management.workflowstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Action Log",
                "verbose_name_plural": "Workflow Action Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workflow_step", "-created_at"],
                        name="product_man_workflo_ee0537_idx",
                    )
                ],
            },
        ),
    ]
