# Generated by Django 4.2.24 on 2025-11-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0011_workflowdocument_workflowactionlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowactionlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("comment_added", "Comment Added"),
                    ("description_updated", "Description Updated"),
                    ("title_updated", "Title Updated"),
                    ("readme_generated", "README Generated"),
                    ("step_completed", "Step Completed"),
                    ("code_change_requested", "Code Change Requested"),
                    ("code_change_completed", "Code Change Completed"),
                    ("document_saved", "Document Saved"),
                ],
                max_length=50,
            ),
        ),
    ]
