# Generated by Django 4.2.24 on 2025-12-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0006_codechangerequest_codex_logs"),
        ("product_management", "0012_alter_workflowactionlog_action_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="repositories",
            field=models.ManyToManyField(
                blank=True,
                help_text="GitHub repositories connected to this product",
                related_name="products",
                to="github.githubrepository",
            ),
        ),
    ]
