# Generated by Django 4.2.24
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0012_alter_workflowactionlog_action_type"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vision",
            name="organization",
            field=models.OneToOneField(
                blank=True,
                help_text="Organization-level vision (one per organization).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vision",
                to="organizations.organization",
            ),
        ),
    ]
