# Generated by Django 4.2.24
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product_management", "0013_vision_organization"),
        ("github", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="repository",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary GitHub repository for this feature.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="features",
                to="github.githubrepository",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="repositories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Linked GitHub repositories for this product.",
                related_name="products",
                to="github.githubrepository",
            ),
        ),
    ]
