# Generated by Django 4.2.24 on 2025-12-18 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0006_codechangerequest_codex_logs"),
        ("product_management", "0013_product_repositories"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="repository",
            field=models.ForeignKey(
                blank=True,
                help_text="GitHub repository used for AI delivery of this feature",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="features",
                to="github.githubrepository",
            ),
        ),
    ]
