# Generated by Django 5.2.7 on 2025-11-07 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.CharField(max_length=255)),
                (
                    "refresh_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("token_type", models.CharField(default="bearer", max_length=50)),
                ("scope", models.TextField(blank=True)),
                ("github_user_id", models.CharField(blank=True, max_length=100)),
                ("github_username", models.CharField(blank=True, max_length=255)),
                ("github_avatar_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github_connection",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "GitHub Connection",
                "verbose_name_plural": "GitHub Connections",
            },
        ),
        migrations.CreateModel(
            name="GitHubRepository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repo_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, null=True)),
                ("html_url", models.URLField()),
                ("clone_url", models.URLField()),
                ("ssh_url", models.CharField(max_length=500)),
                ("private", models.BooleanField(default=False)),
                ("fork", models.BooleanField(default=False)),
                ("language", models.CharField(blank=True, max_length=100, null=True)),
                ("stargazers_count", models.IntegerField(default=0)),
                ("watchers_count", models.IntegerField(default=0)),
                ("forks_count", models.IntegerField(default=0)),
                ("open_issues_count", models.IntegerField(default=0)),
                ("default_branch", models.CharField(default="main", max_length=100)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("pushed_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repositories",
                        to="github.githubconnection",
                    ),
                ),
            ],
            options={
                "verbose_name": "GitHub Repository",
                "verbose_name_plural": "GitHub Repositories",
                "ordering": ["-updated_at"],
                "unique_together": {("connection", "repo_id")},
            },
        ),
    ]
