# Generated by Django 4.2.24 on 2025-11-07 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0002_codechangerequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='githubrepository',
            options={'ordering': ['-created_at'], 'verbose_name': 'GitHub Repository', 'verbose_name_plural': 'GitHub Repositories'},
        ),
        migrations.DeleteModel(
            name='CodeChangeRequest',
        ),
    ]
