# Generated by Django 5.2.7 on 2025-11-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0004_codechangerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="codechangerequest",
            name="execution_log",
            field=models.TextField(
                blank=True, help_text="Detailed execution log", null=True
            ),
        ),
    ]
