# Generated by Django 5.2.7 on 2025-01-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github", "0005_codechangerequest_execution_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="codechangerequest",
            name="codex_logs",
            field=models.TextField(
                blank=True,
                null=True,
                help_text="Raw Codex CLI output",
            ),
        ),
    ]
